### ISSUE TITLE
mu4e-maildirs-extension-force-update doesn't clear cache

### ISSUE THREAD

**Issue by vlevit** [agpchil/mu4e-maildirs-extension#13]
First of all, thank you for very useful extension.

It appeared that for my setup maildir list was never getting updates, even after pressing `u` in mu4e-main-view. The issue seems to be that I run `mu index` outside of Emacs, so when I press `u` `mu4e-update-index` doesn't find new updates, and the fact that the cache is cleared only in `mu4e-index-updated-hook` which is never called in my case. I think we should additionally clear the cache in `mu4e-maildirs-extension-force-update` just before calling `mu4e-update-index` to be sure that after `u` maildir stats are always up-to-date.

**Comment by agpchil** [comment]
Sorry for the late reply.

I'm glad you liked! :)

About the issue I'm not sure if clearing the cache in `mu4e-maildirs-extension-force-update` will really solve this. Even if you clear the cache there, the view probably won't auto update because `mu4e-update-index` don't call the hooks if the index has not changed (so maybe you'll also have to press `g` or reload mu4e manually to view the changes). And trying to clear the cache and update the view at the same time in `mu4e-maildirs-extension-force-update` is not a good idea (the view will get double-updated for people using `mu4e-update-index` in emacs). So what I see here is:

- `mu4e-maildirs-extension-force-update` updates the index (but was really poor named by me, I should named `mu4e-maildirs-extension-update-index` instead or maybe even better to just call `mu4e-update-index` directly). There was a binding to update mail & index (`U`) but none for just update index.
- If you update the index outside the emacs then you'll need a way to just update the view ignoring the cache. It would be great if we could use 'g' (revert-buffer) to avoid adding a new binding but `mu4e` already redefines it to do its own stuff...

So in the end.. maybe the way to solve this is by adding a new action with its own binding or adding a custom wrapper for `revert-buffer` and using `g`.

Does this make sense?

**Comment by vlevit** [comment]
Yes, everything you said does make sense. The issue was that I didn't realize that README and code comments regarding cache update doesn't apply if indexing is done outside of Emacs.

I ended up updating the view in the external script via `emacsclient -e '(my-mu4e-maildirs-update)` (only on index updates) so I don't need to update the view manually.
    
    (defun my-mu4e-maildirs-update ()
      "Clear cache and insert maildirs summary."
      (setq mu4e-maildirs-extension-cached-maildirs-data nil)
      (mu4e-maildirs-extension-update))

I know that I'm updating the view even if the buffer is not active but I haven't noticed any performance issues yet.

Thank you for your suggestions! I think the issue might be closed.

**Comment by agpchil** [comment]
Thank you for reporting this issue and posting your workaround! :)

If you don't mind I like to keep this issue open. So I won't forget that I still need to clean the `-force-update` mess and provide the functionality to update the cache and redisplay the view manually.

 Feel free to report again if something not working for you!

**Comment by vlevit** [comment]
Sure. It would be very nice to have this feature out of the box and even nicer to have it documented. Thank you!

**Comment by agpchil** [comment]
I just pushed some changes in a `devel` branch to allow `mu4e-maildirs-extension-force-update` clear the cache and redisplay using `universal-argument`. So now using `u` should call the `mu4e-update-index` as before, `C-u u` should clear the cache and `C-u C-u u` should clear the cache and redisplay.

To clear the cache and redisplay in you script you can do something like:
```lisp
(mu4e-maildirs-extension-force-update '(16))
``` 

@vlevit is this useful to you? can you try the `devel` branch and see if it works for you?

**Comment by vlevit** [comment]
Yes, it seems to work for me. Thanks!

**Comment by agpchil** [comment]
I wanted to update the README before merging into master. But didn't expect it would take that long...
Anyway, I just created a PR #14 and merged into master. It should be available in MELPA soon.

Thanks again and feel free to report again if something not working for you!

**Comment by agpchil** [comment]
I'm closing this now. But if you want to share your script for others feel free to reopen, PR or whatever :)
