### ISSUE TITLE
Update unread count after reading

### ISSUE THREAD

**Issue by luisbg** [agpchil/mu4e-maildirs-extension#22]
Hi! First of all, this extension makes mu4e's main view so much more useful. Thanks to this I can use mu4e full time.

After I've viewed the headers of a folder and marked a few emails as read (mailing lists) or read them. I go back to the main view with 'q' and mu4-maildirs-extension shows the old unread count.

I need to Update my email to see the real current unread count. Which takes a while since it needs to sync with all the folders in my mail server.

Is there a way to have mu4e-maildirs-extension browse again the folders and recalculate the unread without having to Update mu4e?

**Comment by agpchil** [comment]
Hi! Thanks for the feedback :)

IIRC the index needs to be updated so the `mu` command can see the changes. You can update only the index using `u` key in the main view (instead of using the default `U` which also fetch the mail that mu4e provides).

You probably can also set a hook to force mu4e to auto-update every time you go to the main view. I haven't tested this, but I believe it should work:

```lisp
(defun my-mu4e-maildirs-extension-always-update ()
  (mu4e-maildirs-extension-force-update '(4)))

(add-hook 'mu4e-main-mode-hook 'my-mu4e-maildirs-extension-always-update)
```

BTW, which version of `mu4e-maildirs-extension` are you using? melpa-stable? melpa? git?

**Comment by luisbg** [comment]
I will set that hook and let you know how it goes.

I use mu4-maildirs-extension from git.

Thanks

**Comment by sineer** [comment]
Hi,

Thank you for mu4e-maildir-extension plugin! I like it a lot :+1: 

I had this issue where even when I updated the index by pressing [u] instead of [U] it did run mu indexing but did not update the header view even too I do have (setq mu4e-headers-auto-update t).

For the record, I'm using ./elpa/mu4e-maildirs-extension-20151126.926 with latest spacemacs devel with emacs-25.0.50.1

So I found this issue and I tried the mu4e-main-mode-hook you posted above and now it works like a charm :-)

Thank you very much once more for your plugin and your time!

**Comment by agpchil** [comment]
@sineer Sorry for the late reply and thanks for the feedback!
 I hope it also worked for @luisbg 

> I updated the index by pressing [u] instead of [U] it did run mu indexing but did not update the header view even too I do have (setq mu4e-headers-auto-update t).

I'm a bit confused about this. This extension should only update the main view so the `mu4e-headers-auto-update` should not be related. IIRC the only triggers are the indexing hook and the main mode hook.

**Comment by agpchil** [comment]
@sineer reported this worked so I'm closing this.
Feel free to reopen this issue or open a new one if you need.
Thank you!
