### ISSUE TITLE
Feature request: Only show maildirs with unread messages

### ISSUE THREAD

**Issue by kluge** [agpchil/mu4e-maildirs-extension#28]
Despite using a search based mail client I'm still archiving my mails into way too many folders...

This means that the current maildir list is much too long. I'd mostly be interested in seeing at a glance which maildirs actually have new messages. So I'd want to limit the list to only the maildirs with unread messages.

Would you be interested in supporting that?

**Comment by agpchil** [comment]
Contributions are (almost) always welcome here! :)
 
@gaydenko also reported issues with a large number of maildirs in #24. He suggested a horizontal layout and to hide empty maildirs. Also @punchagan submitted a PR #27 to add a keybinding to jump to a maildir viewing only unread messages. Maybe they'll be interested in some thing like this too. 
 
IMHO, it would be great to add some kind of filtering mechanism instead of just limiting to list only unread maildirs. This way the user could define its own predicate and all maildirs matching that will be listed. A bit more generic :P
 
Feel free to send a PR! :)

**Comment by ayman** [comment]
I think PR #36 addressed and closed this.

**Comment by agpchil** [comment]
Thank you @ayman for commenting this!
